import 'package:catering/models/models.dart';
import 'package:catering/ui/widgets/widgets.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:catering/shared/shared.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'dart:async';
import 'package:flutter/services.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;

// import 'package:get/utils.dart';
// import 'package:get/get.dart';
//import 'package:flutter_spinkit/flutter_spinkit.dart';

part 'package:catering/services/baseapiservices.dart';
part 'package:catering/services/userloginservices.dart';
part 'package:catering/services/apiresponse.dart';
part 'package:catering/models/constanta.dart';
part 'package:catering/models/userloginmodel.dart';
part 'package:catering/models/verificationmodel.dart';

part 'splash_screen.dart';
part 'general_page.dart';
part 'sign_in_page.dart';
part 'sign_up_page.dart';
part 'illustration_page.dart';
part 'success_sign_up_page.dart';
part 'address_page.dart';
part 'forgot_page.dart';
part 'home_page.dart';
part 'kuke_page.dart';
part 'profile_page.dart';
part 'forgotpasswordverification.dart';
part 'reset_password.dart';
part 'change_password.dart';
// part 'order_history_page.dart';
part 'change_profile.dart';
part 'change_password_profile.dart';
part 'kuke_details_page.dart';
part 'payment.dart';
